### ISSUE TITLE
open nx query server side session

### ISSUE THREAD

**Issue by meganhuggett** [wk8/neatx#76]
Hi all, I am quite the Linux dummy and have been connecting to a virtual machine using OpenNX. I have been doing this from both a windows and a mac machine. Up until yesterday it worked beautifully but the second time I tried to connect to my VM yesterday using my windows machine I got an error. I opened OpenNX, entered my username and password, the connecting window pops up, the connection appears to work, authenticates and begins to load, and then it seems to pause and the text reads 'query server side-sessions'. I have tried this from my mac and the same thing happens. From my end (on my mac) I tried to terminate any nx processes that are running, so these are all killed, but I think I need to connect to the VM and kill them from that end - is that correct? If so, how do I do this (in very simple terms)? If not, does anyone have any suggestions as to why this is happening and how I can fix it? Thanks in advance for any help. Megan

**Comment by wk8** [comment]
Hi Megan,

I don't maintain neatx, I'm sorry.

This repo is just a fork of the official repo.

Thanks
